import type { Metadata, Viewport } from "next";
import ClientRootLayout from "./clientRootLayout";

export const metadata: Metadata = {
  manifest: "./manifest.json",
  title: "ECOWATCH APP",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode; 
}) {
  return (
    <ClientRootLayout>
      {children} 
    </ClientRootLayout>
  );
}
